name: Qodana

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 1'

jobs:
  qodana:
    name: 'Qodana'
    runs-on: ubuntu-latest

    environment:
      name: 'Qodana'

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Run Qodana Analysis'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
